export default {
  WALLET_SYSTEM_RUNNING: 'Wallet System is running on PORT',
  INTERNAL_SERVER_ERROR: 'Oops, something broke on the server!!!',
  SUCCESS: 'success',
  FAIL: 'error',
  WELCOME: 'Thanks for dropping by, you are at Wallet system',
  v1: '/api/v1',
  DB_ERROR: 'A database error occurred',
  MODULE_ERROR: 'A module error occurred',
  NOT_FOUND_API: 'Oops, You have reached a dead end',
  INVALID_CREDENTIAL: 'Invalid credentials',
  LOGIN_USER: 'User logged in successfully',
  AUTH_REQUIRED: 'Access denied, a valid access token is required',
  PAYMENT_INITIALIZATION: 'Payment initiated successfully',
  PAYMENT_VERIFICATION: 'Payment verified successfully',
  PAYMENT_SUCCESS: 'payment was successful',
  TRANSFER_SUCCESS: 'transfer was successful',
  CREATE_SUCCESS: (resource: string) => `${resource} created successfully`,
  FETCH_SUCCESS: (resource: string) => `${resource} fetched successfully`,
  RESOURCE_NOT_FOUND: (resource: string) => `${resource} not found`,
  RESOURCE_ALREADY_EXIST: (resource: string) => `${resource} exists already`,
  RESOURCE_CREATE_ERROR_STATUS: (resource: string) => `${resource}_CREATE_ERROR`,
  RESOURCE_FETCH_ERROR_STATUS: (resource: string) => `${resource}_FETCH_ERROR`,
  CREATE_ERROR_MSG: (resource: string) => `Error occured while creating ${resource}`,
};
